#!/usr/bin/env python3
"""Claude Code session registry.

Hooks keep ~/.claude/session-registry.md up to date; Haiku writes each entry's
title, about, left-off and keywords. Design: docs/design.md
"""
import hashlib
import json
import os
import re
import shlex
import shutil
import subprocess
import sys
import tempfile
import time
from contextlib import contextmanager
from datetime import datetime
from pathlib import Path

try:
    import fcntl
except ImportError:  # Windows
    fcntl = None
    import msvcrt

WINDOWS = os.name == "nt"  # picks the resume-command syntax
HOME = Path.home()
REGISTRY = Path(os.environ.get("SESSION_REGISTRY_FILE", HOME / ".claude" / "session-registry.md"))
LOCK = REGISTRY.with_suffix(".lock")
LOG = REGISTRY.with_suffix(".log")
PROJECTS = Path(os.environ.get("SESSION_REGISTRY_PROJECTS", HOME / ".claude" / "projects"))
EVERY = 10      # prompts between summaries
CAP = 20_000    # max transcript characters sent to Haiku
TRIVIAL_MAX = 3 # longest session a "no real work" verdict may hide


# --- transcript reading -------------------------------------------------------

def _text(content):
    if isinstance(content, str):
        return content
    return "\n".join(b.get("text", "") for b in content or [] if isinstance(b, dict) and b.get("type") == "text")


INJECTED = ("<task-notification>", "<local-command-stdout>")  # system messages stored as user lines


def _prompt_text(content):
    """Text of a real user prompt, or None for tool results and injected system messages."""
    if isinstance(content, str):
        text = content
    else:
        blocks = [b for b in content or [] if isinstance(b, dict)]
        if any(b.get("type") == "tool_result" for b in blocks):
            return None
        texts = [b.get("text", "") for b in blocks if b.get("type") == "text"]
        if not texts:
            return None
        text = "\n".join(texts)
    return None if text.lstrip().startswith(INJECTED) else text


def read_transcript(path):
    t = {"prompts": 0, "entrypoint": None, "model": None, "branch": None, "cwd": None,
         "first_ts": None, "last_ts": None, "custom_title": None, "lines": []}
    with open(path, encoding="utf-8", errors="ignore") as fh:
        for raw in fh:
            try:
                d = json.loads(raw)
            except ValueError:
                continue
            if not isinstance(d, dict):
                continue
            kind = d.get("type")
            if kind == "custom-title":
                t["custom_title"] = d.get("customTitle") or t["custom_title"]
            if kind not in ("user", "assistant") or d.get("isSidechain"):
                continue
            t["entrypoint"] = t["entrypoint"] or d.get("entrypoint")
            t["cwd"] = d.get("cwd") or t["cwd"]
            t["branch"] = d.get("gitBranch") or t["branch"]
            if d.get("timestamp"):
                t["first_ts"] = t["first_ts"] or d["timestamp"]
                t["last_ts"] = d["timestamp"]
            msg = d["message"] if isinstance(d.get("message"), dict) else {}
            if kind == "assistant":
                model = msg.get("model") or ""
                if model and not model.startswith("<"):  # "<synthetic>" = local error / limit message
                    t["model"] = model
                text = _text(msg.get("content")).strip()
                if text:
                    t["lines"].append("ASSISTANT: " + text[:600])
            elif not d.get("isMeta") and not d.get("isCompactSummary"):
                text = _prompt_text(msg.get("content"))
                if text is not None:
                    t["prompts"] += 1
                    t["lines"].append("USER: " + text[:1500])
    return t


def skip(t):
    """Automated (Agent SDK / claude -p) and empty sessions never enter the registry."""
    return (t["entrypoint"] or "").startswith("sdk-") or t["prompts"] == 0


def condense(t):
    head = f"Project: {t['cwd']}\nBranch: {t['branch'] or '-'}\n"
    if t["custom_title"]:
        head += f"Custom title: {t['custom_title']}\n"
    body = "\n".join(t["lines"])
    if len(body) > CAP:  # ponytail: keep the opening and the end; the middle of 200+ prompt sessions is dropped
        body = body[:4000] + "\n[...]\n" + body[-(CAP - 4000):]
    return head + "\n" + body


# --- registry file ------------------------------------------------------------

HEADER = ("# Claude Code session registry\n\n"
          "_Newest first. Generated by session_registry.py; hand edits are overwritten. Search with /find-session._\n")
PENDING = "(summary pending)"
STALE = "⚠ transcript deleted (30-day cleanup), not resumable"
MARK = re.compile(r"<!-- session:(\S+) created:(\S+) turns:(\d+) pushed:(\S+)( trivial)? -->$")
FIELD = re.compile(r"- \*\*(.+?):\*\* (.*)$")
APPS = {"cli": "cli", "claude-desktop": "desktop"}
REFRESHED = ("When", "Project", "Model / app", "Resume")
SAFE_ID = re.compile(r"[\w-]+")  # session ids are UUIDs; anything else must not reach a shell command


def local(ts):
    return datetime.fromisoformat(ts.replace("Z", "+00:00")).astimezone()


def tilde(path):
    home = str(HOME)
    return "~" + path[len(home):] if path == home or path.startswith(home + os.sep) else path


def resume_command(cwd, sid):
    if WINDOWS:  # ponytail: "..." and ';' work in PowerShell 5/7 and Git Bash; a '$' or '`' in the path would not
        return f'cd "{cwd}"; claude --resume {sid}'
    home = str(HOME) + "/"  # ~ stays unquoted so the shell still expands it
    where = "~/" + shlex.quote(cwd[len(home):]) if cwd.startswith(home) else shlex.quote(cwd)
    return f"cd {where} && claude --resume {sid}"


def one_line(value):
    return " ".join(str(value).split())


def base_fields(sid, t):
    if not SAFE_ID.fullmatch(sid):
        raise ValueError(f"unsafe session id {sid!r}")
    first, last = local(t["first_ts"]), local(t["last_ts"])
    model = (t["model"] or "unknown").removeprefix("claude-")
    app = APPS.get(t["entrypoint"], t["entrypoint"] or "unknown")
    cwd = t["cwd"] or "."
    return {
        "When": f"{first:%Y-%m-%d %H:%M} → last active {last:%Y-%m-%d %H:%M}",
        "Project": f"{tilde(cwd)} (branch: {t['branch'] or '—'})",
        "Model / app": f"{model} · {app}",
        "About": "—",
        "Left off": "—",
        "Keywords": "—",
        "Resume": f"`{resume_command(cwd, sid)}`",
    }


def new_entry(sid, t):
    return {"id": sid, "created": f"{local(t['first_ts']):%Y-%m-%dT%H:%M}", "turns": 0, "pushed": "-",
            "trivial": False, "title": PENDING, "f": base_fields(sid, t)}


def refresh(e, t):
    """Update the transcript-derived fields; keep title and summary fields."""
    if not e["f"]:  # a collapsed (trivial) entry gets its fields back only from a non-trivial summary
        return
    fresh = base_fields(e["id"], t)
    e["f"].update({k: fresh[k] for k in REFRESHED})


def find(entries, sid):
    return next((e for e in entries if e["id"] == sid), None)


def load():
    if not REGISTRY.exists():
        return []
    entries, cur = [], None
    for line in REGISTRY.read_text(encoding="utf-8").splitlines():
        m = MARK.match(line)
        field = FIELD.match(line)
        if m:
            cur = {"id": m[1], "created": m[2], "turns": int(m[3]), "pushed": m[4],
                   "trivial": bool(m[5]), "title": "", "f": {}}
            entries.append(cur)
        elif cur and line.startswith("## "):
            cur["title"] = line[3:]
        elif cur and field:
            cur["f"][field[1]] = field[2]
    return entries


def render(e):
    flag = " trivial" if e["trivial"] else ""
    mark = f"<!-- session:{e['id']} created:{e['created']} turns:{e['turns']} pushed:{e['pushed']}{flag} -->"
    if e["trivial"]:
        return mark
    return "\n".join([mark, f"## {e['title']}"] + [f"- **{k}:** {v}" for k, v in e["f"].items()])


def mark_stale(entries):
    alive = {p.stem for p in PROJECTS.glob("*/*.jsonl")}
    if not alive:  # projects dir missing or unreadable: never wipe every resume command
        return
    for e in entries:
        if e["id"] not in alive and "Resume" in e["f"]:
            e["f"]["Resume"] = STALE


def save(entries):
    entries.sort(key=lambda e: e["created"], reverse=True)  # stable: equal timestamps keep their order
    tmp = REGISTRY.with_suffix(".tmp")
    tmp.write_text(HEADER + "".join("\n" + render(e) + "\n" for e in entries), encoding="utf-8")
    for _ in range(50):  # Windows refuses to replace a file another process has open; wait for the reader
        try:
            return os.replace(tmp, REGISTRY)
        except PermissionError:
            time.sleep(0.1)
    os.replace(tmp, REGISTRY)  # last try: let the error reach the log


def lock_file(fh):
    """Block until this process holds the lock; it is released when fh closes."""
    if fcntl:
        return fcntl.flock(fh, fcntl.LOCK_EX)
    while True:  # msvcrt gives up after ~10 s of retries; a hook must wait its turn, not fail
        try:
            return msvcrt.locking(fh.fileno(), msvcrt.LK_LOCK, 1)
        except OSError:
            pass


@contextmanager
def locked():
    """Load entries under an exclusive lock and save them on clean exit; an exception skips the save."""
    REGISTRY.parent.mkdir(parents=True, exist_ok=True)
    with open(LOCK, "w") as fh:
        lock_file(fh)
        entries = load()
        yield entries
        mark_stale(entries)
        save(entries)


# --- summary ------------------------------------------------------------------

SYSTEM = "You summarize coding-agent sessions for a searchable registry. Reply with JSON only."
PROMPT = """Summarize this Claude Code session. Return JSON only:
{"title": "<one general sentence, max 10 words>",
 "about": "<2-3 sentences, max 45 words: what the session was about and what was done>",
 "left_off": "<Done | In progress | Abandoned> - <next step, one line>",
 "keywords": ["<3-5 search terms: files, libs, tickets>"],
 "trivial": <true if no substantive work happened (bare login, error only, greeting), else false>}
Title: no trailing period. About: past tense, no "The user...".

TRANSCRIPT:
"""
KEYS = {"title", "about", "left_off", "keywords", "trivial"}


def claude_bin():
    # PATH first, then the native installer's location (claude.exe on Windows)
    return shutil.which("claude") or shutil.which("claude", path=str(HOME / ".local" / "bin")) or "claude"


def call_haiku(text):
    # Lean flags: no settings, plugins, tools, MCP or skills. Default flags cost ~8x more (spec §8).
    cmd = [claude_bin(), "-p", "--model", "haiku", "--output-format", "json", "--no-session-persistence",
           "--setting-sources", "", "--tools", "", "--strict-mcp-config", "--disable-slash-commands",
           "--system-prompt", SYSTEM]
    r = subprocess.run(cmd, input=PROMPT + text, capture_output=True, encoding="utf-8", timeout=120,
                       cwd=tempfile.gettempdir(), env={**os.environ, "SESSION_REGISTRY_CHILD": "1"})
    if r.returncode != 0:
        raise RuntimeError(f"claude -p exited {r.returncode}: {r.stderr.strip()[:300]}")
    return parse_summary(json.loads(r.stdout)["result"])


def parse_summary(result):
    s = json.loads(re.sub(r"^```(?:json)?\s*|\s*```$", "", result.strip()))
    missing = KEYS - set(s)
    if missing:
        raise ValueError(f"summary missing {sorted(missing)}")
    return s


def digest(title):
    return hashlib.sha1(title.encode()).hexdigest()[:8]


def apply_summary(e, s, t, pushed_seen):
    """pushed_seen: the entry's `pushed` when the transcript was read; a push can land while Haiku runs."""
    e["turns"] = t["prompts"]
    # ponytail: a Haiku "no work" verdict only hides short sessions; longer ones are never erased
    e["trivial"] = s["trivial"] is True and t["prompts"] <= TRIVIAL_MAX
    if e["trivial"]:
        log(f"collapsed trivial session {e['id']} ({t['prompts']} prompts)")
        return
    if not e["f"]:  # coming back from a trivial collapse
        e["f"] = base_fields(e["id"], t)
    custom = t["custom_title"]
    # A custom title is the user's /rename only if it differs from every title we pushed. Before our first
    # push it may be the desktop app's own auto title, which Haiku's title replaces.
    renamed = custom and pushed_seen != "-" and digest(custom) not in (pushed_seen, e["pushed"])
    if e["pushed"] == "user" or renamed:
        e["title"], e["pushed"] = one_line(custom or e["title"]), "user"
    else:
        e["title"] = one_line(s["title"]).rstrip(".")
    e["f"]["About"] = one_line(s["about"])
    e["f"]["Left off"] = one_line(s["left_off"])
    e["f"]["Keywords"] = ", ".join(one_line(k) for k in s["keywords"])


def summarize(sid, transcript_path):
    seen = find(load(), sid)  # read before the transcript, so its custom title is judged against this push state
    t = read_transcript(transcript_path)
    s = call_haiku(condense(t))  # outside the lock: takes seconds
    with locked() as entries:
        e = find(entries, sid)
        if e is None:
            e = new_entry(sid, t)
            entries.append(e)
        refresh(e, t)
        apply_summary(e, s, t, seen["pushed"] if seen else "-")


# --- hooks and CLI ------------------------------------------------------------

def spawn(sid, transcript_path):
    """Summarize in a detached process so the hook returns immediately and survives the session exiting."""
    # Windows: no console window for it or the claude -p it runs; own process group so the session's Ctrl+C skips it
    flags = subprocess.CREATE_NO_WINDOW | subprocess.CREATE_NEW_PROCESS_GROUP if os.name == "nt" else 0
    subprocess.Popen([sys.executable, str(Path(__file__).resolve()), "summarize", sid, transcript_path],
                     start_new_session=True, creationflags=flags, stdin=subprocess.DEVNULL,
                     stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)


def on_stop(hook):
    sid, path = hook["session_id"], hook["transcript_path"]
    t = read_transcript(path)
    if skip(t):
        return
    with locked() as entries:
        e = find(entries, sid)
        if e is None:
            entries.append(new_entry(sid, t))
            due = True
        else:
            refresh(e, t)
            # turns == 0: never summarized (first try failed or is still running), so try again
            due = e["turns"] == 0 or t["prompts"] - e["turns"] >= EVERY
    if due:
        spawn(sid, path)


def on_session_end(hook):
    sid, path = hook["session_id"], hook["transcript_path"]
    t = read_transcript(path)
    if skip(t):
        return
    with locked() as entries:
        e = find(entries, sid)
        due = e is None or t["prompts"] > e["turns"]
    if due:
        spawn(sid, path)


def on_prompt(hook):
    """Hook output that pushes a new registry title into Claude's own session title, or None."""
    sid = hook["session_id"]
    with locked() as entries:
        e = find(entries, sid)
        if not e or e["trivial"] or e["pushed"] == "user" or e["title"] in ("", PENDING):
            return None
        if digest(e["title"]) == e["pushed"]:
            return None
        e["pushed"] = digest(e["title"])
    return {"hookSpecificOutput": {"hookEventName": "UserPromptSubmit", "sessionTitle": e["title"]}}


def log(message):
    LOG.parent.mkdir(parents=True, exist_ok=True)
    with open(LOG, "a", encoding="utf-8") as fh:
        fh.write(f"{datetime.now():%Y-%m-%d %H:%M:%S} {message}\n")


def backfill():
    known = {e["id"] for e in load()}
    for path in sorted(PROJECTS.glob("*/*.jsonl")):
        if path.stem in known or skip(read_transcript(path)):
            continue
        try:
            summarize(path.stem, str(path))
            print("added", path.stem, flush=True)
        except Exception as exc:
            log(f"backfill {path.stem}: {exc!r}")
            print("failed", path.stem, exc, flush=True)


def main(argv):
    cmd = argv[1] if len(argv) > 1 else ""
    try:
        if os.environ.get("SESSION_REGISTRY_CHILD") == "1":
            return
        if cmd == "summarize":
            summarize(argv[2], argv[3])
        elif cmd == "backfill":
            backfill()
        elif cmd == "stop":
            on_stop(json.load(sys.stdin))
        elif cmd == "session-end":
            on_session_end(json.load(sys.stdin))
        elif cmd == "prompt":
            out = on_prompt(json.load(sys.stdin))
            if out:
                print(json.dumps(out))
        else:
            log(f"unknown command {cmd!r}")
    except Exception as exc:  # ponytail: a hook must never break a session; the log is the only error channel
        log(f"{cmd}: {exc!r}")


if __name__ == "__main__":
    main(sys.argv)
